profile-name: main

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://3.36.78.190:3306/project?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: Wjddlsdnr12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080
  tomcat:
    keep-alive-timeout: 2048
